
# SETTINGS
#server: 
#  port: 8080
#  servlet: 
#    context-path: /movies

#GENERAL
spring:
  application.name: Golden Raspberry Awards
  h2:
    console:
      enabled: true

  
#DATA SOURCE  
  datasource:
    username: cine
    password: cine 
#    url: jdbc:h2:mem:movies;DB_CLOSE_DELAY=-1;;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:movies;
    driver-class-name: org.h2.Driver
    
#JPA
  jpa:
    
    hibernate.ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format-sql: true